### ISSUE TITLE
我安装了插件，也下载了源码，但是我看里面的requestId是你自己的id吧，插件并没有修改id的地方，这个id我不清楚是否是用户id，如果不修改的话，那不就成了帮你抢狗的工具了吗，另外说一句，还是很感谢开源

### ISSUE THREAD

**Issue by LeachZhou** [tabalt/baidu-pet-chain-buyer#4]
我安装了插件，也下载了源码，但是我看里面的requestId是你自己的id吧，插件并没有修改id的地方，这个id我不清楚是否是用户id，如果不修改的话，那不就成了帮你抢狗的工具了吗，另外说一句，还是很感谢开源

**Comment by tabalt** [comment]
requestId只是个时间戳，接口没校验，于是就写死了。下单都是通过你登录百度帐号后浏览器cookie操作的，请放心使用

**Comment by diong** [comment]
也是，不然id跟cookie没对应，应该是抢不了
